//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Management_Application.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatisticDate
    {
        public Nullable<int> TotalSales { get; set; }
        public Nullable<int> TotalImport { get; set; }
        public Nullable<float> TotalPrice { get; set; }
        public System.DateTime DateSales { get; set; }
    }
}
